export interface CountryCode {
  code: string;
  dial: string;
  flag: string;
  minLength: number;
  maxLength: number;
}

export const countryCodes: CountryCode[] = [
  // Middle East & North Africa (priority)
  { code: 'SY', dial: '+963', flag: '🇸🇾', minLength: 9, maxLength: 9 },
  { code: 'LB', dial: '+961', flag: '🇱🇧', minLength: 7, maxLength: 8 },
  { code: 'EG', dial: '+20', flag: '🇪🇬', minLength: 10, maxLength: 10 },
  { code: 'JO', dial: '+962', flag: '🇯🇴', minLength: 9, maxLength: 9 },
  { code: 'IQ', dial: '+964', flag: '🇮🇶', minLength: 10, maxLength: 10 },
  { code: 'PS', dial: '+970', flag: '🇵🇸', minLength: 9, maxLength: 9 },
  { code: 'SA', dial: '+966', flag: '🇸🇦', minLength: 9, maxLength: 9 },
  { code: 'AE', dial: '+971', flag: '🇦🇪', minLength: 9, maxLength: 9 },
  { code: 'KW', dial: '+965', flag: '🇰🇼', minLength: 8, maxLength: 8 },
  { code: 'QA', dial: '+974', flag: '🇶🇦', minLength: 8, maxLength: 8 },
  { code: 'BH', dial: '+973', flag: '🇧🇭', minLength: 8, maxLength: 8 },
  { code: 'OM', dial: '+968', flag: '🇴🇲', minLength: 8, maxLength: 8 },
  { code: 'YE', dial: '+967', flag: '🇾🇪', minLength: 9, maxLength: 9 },
  { code: 'LY', dial: '+218', flag: '🇱🇾', minLength: 9, maxLength: 10 },
  { code: 'TN', dial: '+216', flag: '🇹🇳', minLength: 8, maxLength: 8 },
  { code: 'DZ', dial: '+213', flag: '🇩🇿', minLength: 9, maxLength: 9 },
  { code: 'MA', dial: '+212', flag: '🇲🇦', minLength: 9, maxLength: 9 },
  { code: 'SD', dial: '+249', flag: '🇸🇩', minLength: 9, maxLength: 9 },
  // Turkey
  { code: 'TR', dial: '+90', flag: '🇹🇷', minLength: 10, maxLength: 10 },
  // Europe
  { code: 'DE', dial: '+49', flag: '🇩🇪', minLength: 10, maxLength: 11 },
  { code: 'FR', dial: '+33', flag: '🇫🇷', minLength: 9, maxLength: 9 },
  { code: 'GB', dial: '+44', flag: '🇬🇧', minLength: 10, maxLength: 10 },
  { code: 'IT', dial: '+39', flag: '🇮🇹', minLength: 9, maxLength: 10 },
  { code: 'ES', dial: '+34', flag: '🇪🇸', minLength: 9, maxLength: 9 },
  { code: 'NL', dial: '+31', flag: '🇳🇱', minLength: 9, maxLength: 9 },
  { code: 'BE', dial: '+32', flag: '🇧🇪', minLength: 9, maxLength: 9 },
  { code: 'SE', dial: '+46', flag: '🇸🇪', minLength: 9, maxLength: 10 },
  { code: 'NO', dial: '+47', flag: '🇳🇴', minLength: 8, maxLength: 8 },
  { code: 'DK', dial: '+45', flag: '🇩🇰', minLength: 8, maxLength: 8 },
  { code: 'FI', dial: '+358', flag: '🇫🇮', minLength: 9, maxLength: 10 },
  { code: 'AT', dial: '+43', flag: '🇦🇹', minLength: 10, maxLength: 11 },
  { code: 'CH', dial: '+41', flag: '🇨🇭', minLength: 9, maxLength: 9 },
  { code: 'PL', dial: '+48', flag: '🇵🇱', minLength: 9, maxLength: 9 },
  { code: 'PT', dial: '+351', flag: '🇵🇹', minLength: 9, maxLength: 9 },
  { code: 'GR', dial: '+30', flag: '🇬🇷', minLength: 10, maxLength: 10 },
  { code: 'CZ', dial: '+420', flag: '🇨🇿', minLength: 9, maxLength: 9 },
  { code: 'RO', dial: '+40', flag: '🇷🇴', minLength: 9, maxLength: 9 },
  { code: 'HU', dial: '+36', flag: '🇭🇺', minLength: 9, maxLength: 9 },
  { code: 'IE', dial: '+353', flag: '🇮🇪', minLength: 9, maxLength: 9 },
  { code: 'UA', dial: '+380', flag: '🇺🇦', minLength: 9, maxLength: 9 },
  { code: 'RU', dial: '+7', flag: '🇷🇺', minLength: 10, maxLength: 10 },
  // Americas
  { code: 'US', dial: '+1', flag: '🇺🇸', minLength: 10, maxLength: 10 },
  { code: 'CA', dial: '+1', flag: '🇨🇦', minLength: 10, maxLength: 10 },
  { code: 'MX', dial: '+52', flag: '🇲🇽', minLength: 10, maxLength: 10 },
  { code: 'BR', dial: '+55', flag: '🇧🇷', minLength: 10, maxLength: 11 },
  { code: 'AR', dial: '+54', flag: '🇦🇷', minLength: 10, maxLength: 10 },
  { code: 'CO', dial: '+57', flag: '🇨🇴', minLength: 10, maxLength: 10 },
  { code: 'CL', dial: '+56', flag: '🇨🇱', minLength: 9, maxLength: 9 },
  // Asia & Pacific
  { code: 'CN', dial: '+86', flag: '🇨🇳', minLength: 11, maxLength: 11 },
  { code: 'IN', dial: '+91', flag: '🇮🇳', minLength: 10, maxLength: 10 },
  { code: 'PK', dial: '+92', flag: '🇵🇰', minLength: 10, maxLength: 10 },
  { code: 'JP', dial: '+81', flag: '🇯🇵', minLength: 10, maxLength: 10 },
  { code: 'KR', dial: '+82', flag: '🇰🇷', minLength: 10, maxLength: 11 },
  { code: 'ID', dial: '+62', flag: '🇮🇩', minLength: 10, maxLength: 12 },
  { code: 'MY', dial: '+60', flag: '🇲🇾', minLength: 9, maxLength: 10 },
  { code: 'PH', dial: '+63', flag: '🇵🇭', minLength: 10, maxLength: 10 },
  { code: 'TH', dial: '+66', flag: '🇹🇭', minLength: 9, maxLength: 9 },
  { code: 'AU', dial: '+61', flag: '🇦🇺', minLength: 9, maxLength: 9 },
  { code: 'NZ', dial: '+64', flag: '🇳🇿', minLength: 9, maxLength: 10 },
  // Africa
  { code: 'NG', dial: '+234', flag: '🇳🇬', minLength: 10, maxLength: 10 },
  { code: 'ZA', dial: '+27', flag: '🇿🇦', minLength: 9, maxLength: 9 },
  { code: 'KE', dial: '+254', flag: '🇰🇪', minLength: 9, maxLength: 9 },
  { code: 'GH', dial: '+233', flag: '🇬🇭', minLength: 9, maxLength: 9 },
  { code: 'ET', dial: '+251', flag: '🇪🇹', minLength: 9, maxLength: 9 },
  { code: 'SO', dial: '+252', flag: '🇸🇴', minLength: 8, maxLength: 8 },
  { code: 'MR', dial: '+222', flag: '🇲🇷', minLength: 8, maxLength: 8 },
];

export const countryNames: Record<string, { en: string; ar: string }> = {
  SY: { en: 'Syria', ar: 'سوريا' },
  LB: { en: 'Lebanon', ar: 'لبنان' },
  EG: { en: 'Egypt', ar: 'مصر' },
  JO: { en: 'Jordan', ar: 'الأردن' },
  IQ: { en: 'Iraq', ar: 'العراق' },
  PS: { en: 'Palestine', ar: 'فلسطين' },
  SA: { en: 'Saudi Arabia', ar: 'السعودية' },
  AE: { en: 'UAE', ar: 'الإمارات' },
  KW: { en: 'Kuwait', ar: 'الكويت' },
  QA: { en: 'Qatar', ar: 'قطر' },
  BH: { en: 'Bahrain', ar: 'البحرين' },
  OM: { en: 'Oman', ar: 'عُمان' },
  YE: { en: 'Yemen', ar: 'اليمن' },
  LY: { en: 'Libya', ar: 'ليبيا' },
  TN: { en: 'Tunisia', ar: 'تونس' },
  DZ: { en: 'Algeria', ar: 'الجزائر' },
  MA: { en: 'Morocco', ar: 'المغرب' },
  SD: { en: 'Sudan', ar: 'السودان' },
  TR: { en: 'Turkey', ar: 'تركيا' },
  DE: { en: 'Germany', ar: 'ألمانيا' },
  FR: { en: 'France', ar: 'فرنسا' },
  GB: { en: 'UK', ar: 'بريطانيا' },
  IT: { en: 'Italy', ar: 'إيطاليا' },
  ES: { en: 'Spain', ar: 'إسبانيا' },
  NL: { en: 'Netherlands', ar: 'هولندا' },
  BE: { en: 'Belgium', ar: 'بلجيكا' },
  SE: { en: 'Sweden', ar: 'السويد' },
  NO: { en: 'Norway', ar: 'النرويج' },
  DK: { en: 'Denmark', ar: 'الدنمارك' },
  FI: { en: 'Finland', ar: 'فنلندا' },
  AT: { en: 'Austria', ar: 'النمسا' },
  CH: { en: 'Switzerland', ar: 'سويسرا' },
  PL: { en: 'Poland', ar: 'بولندا' },
  PT: { en: 'Portugal', ar: 'البرتغال' },
  GR: { en: 'Greece', ar: 'اليونان' },
  CZ: { en: 'Czech Republic', ar: 'التشيك' },
  RO: { en: 'Romania', ar: 'رومانيا' },
  HU: { en: 'Hungary', ar: 'المجر' },
  IE: { en: 'Ireland', ar: 'أيرلندا' },
  UA: { en: 'Ukraine', ar: 'أوكرانيا' },
  RU: { en: 'Russia', ar: 'روسيا' },
  US: { en: 'USA', ar: 'أمريكا' },
  CA: { en: 'Canada', ar: 'كندا' },
  MX: { en: 'Mexico', ar: 'المكسيك' },
  BR: { en: 'Brazil', ar: 'البرازيل' },
  AR: { en: 'Argentina', ar: 'الأرجنتين' },
  CO: { en: 'Colombia', ar: 'كولومبيا' },
  CL: { en: 'Chile', ar: 'تشيلي' },
  CN: { en: 'China', ar: 'الصين' },
  IN: { en: 'India', ar: 'الهند' },
  PK: { en: 'Pakistan', ar: 'باكستان' },
  JP: { en: 'Japan', ar: 'اليابان' },
  KR: { en: 'South Korea', ar: 'كوريا الجنوبية' },
  ID: { en: 'Indonesia', ar: 'إندونيسيا' },
  MY: { en: 'Malaysia', ar: 'ماليزيا' },
  PH: { en: 'Philippines', ar: 'الفلبين' },
  TH: { en: 'Thailand', ar: 'تايلاند' },
  AU: { en: 'Australia', ar: 'أستراليا' },
  NZ: { en: 'New Zealand', ar: 'نيوزيلندا' },
  NG: { en: 'Nigeria', ar: 'نيجيريا' },
  ZA: { en: 'South Africa', ar: 'جنوب أفريقيا' },
  KE: { en: 'Kenya', ar: 'كينيا' },
  GH: { en: 'Ghana', ar: 'غانا' },
  ET: { en: 'Ethiopia', ar: 'إثيوبيا' },
  SO: { en: 'Somalia', ar: 'الصومال' },
  MR: { en: 'Mauritania', ar: 'موريتانيا' },
};
